CREATE TABLE IF NOT EXISTS T_CODE_GROUP (
  `CD_GRP` varchar(50) DEFAULT NULL,
  `HPOS_CD_GRP` varchar(50) DEFAULT NULL,
  `USE_YN` varchar(1) DEFAULT NULL,
  `CD_GRP_NM` varchar(100) DEFAULT NULL,
  `CD_GRP_DSCR` varchar(500) DEFAULT NULL,
  `REG_DT` timestamp NOT NULL,
  `REG_USER_ID` varchar(50) DEFAULT NULL,
  `UPD_DT` timestamp NULL DEFAULT NULL,
  `UPD_USER_ID` varchar(50) DEFAULT NULL
)